"""Cross-runtime keyring vectors: the committed fixtures ARE the browser contract.

Both fixtures are generated by ``scripts/gen_keyring_vectors.py`` from FIXED seeds (key A =
32 x ``0x01``, key B = 32 x ``0x02``); Ed25519 is deterministic, so regeneration reproduces
them byte for byte.

- ``tests/fixtures/keyring_vectors.json`` is SHARED: the browser runtime commits the exact
  same bytes, so its sha256 is pinned here. Its verdicts are asserted through the same
  pointer-stage checks ``sync_index`` runs (:func:`~edgeproc.bundles.sync.verify_pointer`).
- ``tests/fixtures/keyring_scenarios.json`` is Python's wider matrix over a REAL manifest:
  every case runs a complete ``sync_index`` against a real origin.

In both, derived values re-derive through the shipped library, and every verdict is data the
generator DECLARES — never one the library computed for itself.
"""

from __future__ import annotations

import base64
import hashlib
import importlib.util
import json
from collections.abc import Callable
from pathlib import Path
from types import ModuleType
from typing import Any

import pytest
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from edgeproc.bundles.adapters import FilesystemAdapter
from edgeproc.bundles.cas import FilesystemCacheStore, RollbackError
from edgeproc.bundles.chunking import GearCDC
from edgeproc.bundles.keyring import KeyringVerifier, parse_keyring
from edgeproc.bundles.manifest import VersionPointer, pointer_signing_bytes
from edgeproc.bundles.publish import build_bundle
from edgeproc.bundles.signing import (
    Ed25519Signer,
    Ed25519Verifier,
    KeyRevokedError,
    SignatureError,
    UnknownKeyError,
    key_id_for,
)
from edgeproc.bundles.sync import PointerExpiredError, sync_index, verify_pointer

_ROOT = Path(__file__).resolve().parents[2]
_FIXTURES = _ROOT / "tests" / "fixtures"
_SHARED = _FIXTURES / "keyring_vectors.json"
_SCENARIOS = _FIXTURES / "keyring_scenarios.json"
_GENERATOR = _ROOT / "scripts" / "gen_keyring_vectors.py"
#: The browser runtime commits the identical file; a change on either side must change both.
_SHARED_SHA256 = "4d4dd0b67315a18a0f827d44ec9beb2fa0a410ff04ab904b071aa6f138af3d49"
_SEEDS = {"A": b"\x01" * 32, "B": b"\x02" * 32}

_REFUSALS: dict[str, type[Exception]] = {
    "key_revoked": KeyRevokedError,
    "unknown_key": UnknownKeyError,
    "signature_error": SignatureError,
    "expired": PointerExpiredError,
    "rollback": RollbackError,
}


def _generator() -> ModuleType:
    spec = importlib.util.spec_from_file_location("gen_keyring_vectors", _GENERATOR)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _load(path: Path) -> dict[str, Any]:
    loaded: dict[str, Any] = json.loads(path.read_bytes())
    return loaded


def _public(name: str) -> bytes:
    return Ed25519PrivateKey.from_private_bytes(_SEEDS[name]).public_key().public_bytes_raw()


def _assert_verdict(expected: str, action: Callable[[], None]) -> None:
    """``ok`` must not raise; a refusal must raise EXACTLY its class (not just a base)."""
    if expected == "ok":
        action()
        return
    with pytest.raises(_REFUSALS[expected]) as exc:
        action()
    assert type(exc.value) is _REFUSALS[expected]


# --- the generator reproduces both committed files --------------------------------------


def test_generator_reproduces_both_fixtures_byte_for_byte() -> None:
    texts = _generator().rendered()
    assert texts["keyring_vectors.json"].encode("utf-8") == _SHARED.read_bytes()
    assert texts["keyring_scenarios.json"].encode("utf-8") == _SCENARIOS.read_bytes()


def test_shared_file_is_the_browser_runtimes_exact_bytes() -> None:
    raw = _SHARED.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == _SHARED_SHA256
    # Compact, key-sorted canonical JSON with no trailing newline.
    assert raw == json.dumps(_load(_SHARED), sort_keys=True, separators=(",", ":")).encode()


def test_generator_check_mode_passes_on_the_committed_files_and_fails_on_drift(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    gen = _generator()
    assert gen.main(["--check", "--out-dir", str(_FIXTURES)]) == 0
    assert gen.main(["--out-dir", str(tmp_path)]) == 0
    for name in ("keyring_vectors.json", "keyring_scenarios.json"):
        assert (tmp_path / name).read_bytes() == (_FIXTURES / name).read_bytes()
    (tmp_path / "keyring_vectors.json").write_text("{}", encoding="utf-8")
    (tmp_path / "keyring_scenarios.json").unlink()
    assert gen.main(["--check", "--out-dir", str(tmp_path)]) == 1
    err = capsys.readouterr().err
    assert "keyring_vectors.json is stale" in err
    assert "keyring_scenarios.json is stale" in err


# --- the shared vectors -----------------------------------------------------------------


def _shared_pointer(name: str) -> VersionPointer:
    return VersionPointer.model_validate(_load(_SHARED)["pointers"][name]["pointer"])


def test_shared_key_ids_derive_from_the_fixed_seeds() -> None:
    for name in ("A", "B"):
        public = _public(name)
        assert _load(_SHARED)["key_ids"][name] == key_id_for(public)
        assert key_id_for(public) == hashlib.sha256(public).hexdigest()[:16]


def test_shared_keyrings_parse_strictly_with_the_agreed_membership() -> None:
    ids = _load(_SHARED)["key_ids"]
    rings = {
        n: parse_keyring(json.dumps(d).encode()) for n, d in _load(_SHARED)["keyrings"].items()
    }
    assert [e.key_id for e in rings["ab"].keys] == sorted([ids["A"], ids["B"]])
    assert rings["ab"].revoked == []
    assert [e.key_id for e in rings["b_revoked_a"].keys] == [ids["B"]]
    assert rings["b_revoked_a"].revoked == [ids["A"]]


def test_shared_pointers_carry_the_specified_fields() -> None:
    ids = _load(_SHARED)["key_ids"]
    a, b, c, d = (_shared_pointer(n) for n in "abcd")
    for pointer in (a, b, c, d):
        assert (pointer.manifest_hash, pointer.version) == ("0" * 64, "2026-01-01")
        assert (pointer.bundle_id, pointer.channel) == ("vectors", "stable")
    assert (a.sequence, a.key_id, a.expires_at) == (1, None, None)
    assert (b.sequence, b.key_id, b.expires_at) == (2, ids["A"], None)
    assert (c.sequence, c.key_id, c.expires_at) == (3, ids["B"], None)
    assert (d.sequence, d.key_id, d.expires_at) == (4, ids["B"], 1767225600)


@pytest.mark.parametrize(("name", "signer"), [("a", "A"), ("b", "A"), ("c", "B"), ("d", "B")])
def test_shared_preimage_and_signature_rederive(name: str, signer: str) -> None:
    vector = _load(_SHARED)["pointers"][name]
    pointer = _shared_pointer(name)
    preimage = pointer_signing_bytes(pointer)
    assert preimage.hex() == vector["preimage_hex"]
    assert base64.b64decode(pointer.signature).hex() == vector["signature_hex"]
    Ed25519Verifier.from_public_bytes(_public(signer)).verify(preimage, pointer.signature)
    # Ed25519 is deterministic: re-signing the preimage reproduces the exact signature.
    assert Ed25519Signer.from_private_bytes(_SEEDS[signer]).sign(preimage) == pointer.signature
    # The browser's pointer object is the Python wire form minus null identity fields.
    wire = json.loads(pointer.model_dump_json())
    assert {k: v for k, v in wire.items() if v is not None} == vector["pointer"]


def _shared_cases() -> list[tuple[str, str, str, str]]:
    return [
        (ring, now, name, verdict)
        for ring, by_now in _load(_SHARED)["outcomes"].items()
        for now, by_pointer in by_now.items()
        for name, verdict in by_pointer.items()
    ]


def test_shared_outcomes_are_the_agreed_matrix() -> None:
    assert _load(_SHARED)["outcomes"] == {
        "b_revoked_a": {
            "1767225599": {"a": "signature_error", "b": "key_revoked", "c": "ok", "d": "ok"},
            "1767225600": {"a": "signature_error", "b": "key_revoked", "c": "ok", "d": "expired"},
        }
    }


@pytest.mark.parametrize(("ring", "now", "name", "verdict"), _shared_cases())
def test_shared_outcome_is_what_the_verifier_does(
    ring: str, now: str, name: str, verdict: str
) -> None:
    keyring = parse_keyring(json.dumps(_load(_SHARED)["keyrings"][ring]).encode())

    def check() -> None:
        verify_pointer(_shared_pointer(name), KeyringVerifier(keyring), clock=lambda: float(now))

    _assert_verdict(verdict, check)


# --- the scenario matrix, through a complete sync ---------------------------------------


def _scenario_pointer(name: str) -> VersionPointer:
    return VersionPointer.model_validate_json(_load(_SCENARIOS)["pointers"][name]["wire_json"])


@pytest.mark.parametrize("name", ["a", "b", "c", "d"])
def test_scenario_pointers_rederive_and_match_their_shared_twins(name: str) -> None:
    vector = _load(_SCENARIOS)["pointers"][name]
    pointer = _scenario_pointer(name)
    assert pointer_signing_bytes(pointer).hex() == vector["preimage_hex"]
    assert base64.b64decode(pointer.signature).hex() == vector["signature_hex"]
    assert pointer.model_dump_json() == vector["wire_json"]
    # Only the manifest hash differs from the shared vector.
    shared = _shared_pointer(name)
    assert pointer.model_copy(update={"manifest_hash": "0" * 64, "signature": ""}) == (
        shared.model_copy(update={"signature": ""})
    )


def test_scenario_verdict_vocabulary_is_the_shared_one_plus_rollback() -> None:
    verdicts = {case["expected"] for case in _load(_SCENARIOS)["cases"]}
    assert verdicts == {"ok", *_REFUSALS}


def _origin(tmp_path: Path, pointer: VersionPointer) -> Path:
    """Lay out the scenarios' real manifest + chunk, then serve ``pointer`` as ``latest``."""
    origin = tmp_path / "origin"
    payload = _load(_SCENARIOS)["payload"]
    throwaway = Ed25519Signer(Ed25519PrivateKey.from_private_bytes(b"\x09" * 32))
    built = build_bundle(
        files={path: text.encode("utf-8") for path, text in payload["files"].items()},
        store=FilesystemCacheStore(origin),
        chunker=GearCDC(),
        signer=throwaway,
        bundle_id=payload["bundle_id"],
        version=payload["version"],
    )
    assert built.manifest_hash == _load(_SCENARIOS)["manifest_hash"]
    (origin / "latest").write_bytes(pointer.model_dump_json().encode("utf-8"))
    return origin


def _case_id(case: dict[str, Any]) -> str:
    return (
        f"{case['ring']}-{case['pointer']}-{case['now']}-floor_{case['floor']}-{case['expected']}"
    )


@pytest.mark.parametrize("case", _load(_SCENARIOS)["cases"], ids=_case_id)
def test_every_scenario_is_what_a_real_sync_does(tmp_path: Path, case: dict[str, Any]) -> None:
    keyring = parse_keyring(json.dumps(_load(_SCENARIOS)["keyrings"][case["ring"]]).encode())
    cache = FilesystemCacheStore(tmp_path / "cache")
    if case["floor"] is not None:
        cache.promote(_scenario_pointer(case["floor"]))
    before = cache.read_active()
    origin = _origin(tmp_path, _scenario_pointer(case["pointer"]))

    def run() -> None:
        sync_index(
            base_url=str(origin),
            store=cache,
            adapter=FilesystemAdapter(),
            verifier=KeyringVerifier(keyring),
            expected_bundle_id="vectors",
            expected_channel="stable",
            clock=lambda: float(case["now"]),
        )

    _assert_verdict(case["expected"], run)
    expected_active = _scenario_pointer(case["pointer"]) if case["expected"] == "ok" else before
    assert cache.read_active() == expected_active
